---
title: "N Modeling"
author: "Ryan Hill"
date: "7/22/2019"
output: 
  html_document: 
    theme: yeti
---

## TN out ~ TN in


```{r, eval=F}
nmodel_dir <- 'D:/WorkFolder/WetlandConnectivity/WetConnect_Apr2019/nitrogen-modeling/'
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

#Riparian catchment goes into Canada
#ndata[ndata$COMID == 24120694, ]
ndata <- ndata[ndata$COMID != 24120694, ]
#Splitcat = single pixel at bottom of catchment
ndata <- ndata[ndata$SITE_ID != 'FW08MD001', ]

ndata$NRWtKgN <- ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$NRSubWtKgN <- ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN

tmp <- ndata[, grep('WtAreaHa', names(ndata), value=T)]
head(tmp)
#tmp$WsAreaHa <- ndata$WsAreaHa
tmp$NWtAreaHa <- ndata$WsAreaHa - rowSums(tmp)
tmp <- (tmp / ndata$WsAreaHa)*100
tmp <- log10(tmp+1)
tmp$WsAreaHa <- log10(ndata$WsAreaHa+1)

tmp$TN <- ndata$TN
tmp$lg_TN <- log10(tmp$TN)

#tmp[grep('WtKgN', names(tmp), value=T)] <- (tmp[grep('WtKgN', names(tmp), value=T)] / tmp$AllKgNWs)*100

#tmp$NwKgNWs <- (tmp$NwKgNWs / tmp$AllKgNWs)*100


summary(lm(lg_TN ~  RiparWtAreaHa+ NRSurWtAreaHa+ NRSubPdWtAreaHa+ NRSubWdWtAreaHa+ NWtAreaHa, data=tmp))
plot(lg_TN ~  RiparWtKgN, data=tmp)

tmp[grep('KgN', names(ndata), value=T)] <- log10(tmp[grep('KgN', names(ndata), value=T)] + 1)
names(tmp[]) <- paste0('lg_', grep('KgN', names(ndata), value=T))

tmp <- data.frame(lg_TNKgYr=log10(ndata$TNKgYr+1), tmp)

# summary(lm(lg_TNKgYr ~ lg_AllKgNWs, data=tmp))
# 
# summary(lm(lg_TNKgYr ~ lg_AllKgNWs+offset(lg_AllKgNWs), data=tmp))
# 
# 
# summary(lm(lg_TNKgYr ~ lg_WtKgNWs+lg_NwKgNWs, data=tmp))
# summary(lm(lg_TNKgYr ~ 
#              lg_WtKgNWs+offset(lg_WtKgNWs)+
#              lg_NwKgNWs+offset(lg_NwKgNWs), data=tmp))
# 
# 
# summary(lm(lg_TNKgYr ~ lg_RiparWtKgN+lg_NRWtKgN+lg_NwKgNWs, data=tmp))
# summary(lm(lg_TNKgYr ~ 
#              lg_RiparWtKgN+offset(lg_RiparWtKgN)+
#              lg_NRWtKgN+offset(lg_NRWtKgN)+
#              lg_NwKgNWs+offset(lg_NwKgNWs), data=tmp))


summary(lm(lg_TNKgYr ~ lg_RiparWtKgN+lg_NRSurWtKgN+lg_NRSubWtKgN+lg_NwKgNWs, data=tmp))
summary(lm(lg_TNKgYr ~ 
             lg_RiparWtKgN+offset(lg_RiparWtKgN)+
             lg_NRSurWtKgN+offset(lg_NRSurWtKgN)+
             lg_NRSubWtKgN+offset(lg_NRSubWtKgN)+
             lg_NwKgNWs+offset(lg_NwKgNWs), data=tmp))



# summary(lm(lg_TNKgYr ~ lg_RiparWtKgN+lg_NRSurWtKgN+lg_NRSubPdWtKgN+lg_NRSubWdWtKgN+lg_NwKgNWs, data=tmp))
# summary(lm(lg_TNKgYr ~ 
#              lg_RiparWtKgN+offset(lg_RiparWtKgN)+
#              lg_NRSurWtKgN+offset(lg_NRSurWtKgN)+
#              lg_NRSubPdWtKgN+offset(lg_NRSubPdWtKgN)+
#              lg_NRSubWdWtKgN+offset(lg_NRSubWdWtKgN)+
#              lg_NwKgNWs+offset(lg_NwKgNWs), data=tmp))



```


## Divide watershed area (Y = N concentration)

```{r, eval=F}
nmodel_dir <- 'D:/WorkFolder/WetlandConnectivity/WetConnect_Apr2019/nitrogen-modeling/'
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

#Riparian catchment goes into Canada
#ndata[ndata$COMID == 24120694, ]
ndata <- ndata[ndata$COMID != 24120694, ]
#Splitcat = single pixel at bottom of catchment
ndata <- ndata[ndata$SITE_ID != 'FW08MD001', ]

ndata$lg_TN <- log10(ndata$TN)

#Model1 data
ndata$lg_AllKgNWs_wsha <- log10((ndata$AllKgNWs / (ndata$WsAreaHa+1))+1)

#Model2 data
ndata$WtKgN <- ndata$RiparWtKgN + ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$lg_WtKgN_wsha <- log10((ndata$WtKgN / (ndata$WsAreaHa))+1)
ndata$lg_NwKgNWs_wsha <- log10(ndata$NwKgNWs / ((ndata$WsAreaHa)+1))

#Model3 data
ndata$NRWtKgN <- ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
#ndata$NRWtArea <- ndata$NRSurWtAreaHa + ndata$NRSubPdWtAreaHa + ndata$NRSubWdWtAreaHa
ndata$lg_NRWtKgN_wsha <- log10((ndata$NRWtKgN / (ndata$WsAreaHa))+1)

#Model4 data
ndata$NRSubWtKgN <- ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
#ndata$NRSubWtArea <- ndata$NRSubPdWtAreaHa + ndata$NRSubWdWtAreaHa
ndata$lg_NRSubWtKgN_wsha <- log10((ndata$NRSubWtKgN / (ndata$WsAreaHa))+1)

#ndata$test <- ndata$RiparWtKgN + ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN

# ndata$NRWtKgN <- ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
# ndata$lg_NRWtKgN_wsha <- log10((ndata$NRWtKgN / ndata$WsAreaHa)+1)
# ndata$NRSubWtKgN <- ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
# ndata$lg_NRSubWtKgN_wsha <- log10((ndata$NRSubWtKgN / ndata$WsAreaHa)+1)
# ndata$lg_WtKgNWs_wsha <- log10((ndata$WtKgNWs / ndata$WsAreaHa)+1)

Types <- c('Ripar','NRSur','NRSubPd','NRSubWd')
for(i in 1:length(Types)){
  wt <- paste0(Types[i], c('WtKgN_wsha','WtKgN'))
  ndata[paste0('lg_',wt[1])] <- log10((ndata[wt[2]] / ndata$WsAreaHa)+1)
}

ndata$lg_NwKgNWs_wsha <- log10((ndata$NwKgNWs / ndata$WsAreaHa)+1)
ndata$lg_AllKgNWs_wsha <- log10((ndata$AllKgNWs / ndata$WsAreaHa)+1)


#cor(ndata[, c(30:36)])
#cor(ndata[, c('lg_WtKgN_wtha','lg_NwKgNWs_nwtha')])
summary(lm(lg_TN ~ lg_AllKgNWs_wsha, data=ndata))
summary(lm(lg_TN ~ lg_WtKgN_wsha+lg_NwKgNWs_wsha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wsha+lg_NRWtKgN_wsha+lg_NwKgNWs_wsha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wsha+lg_NRSurWtKgN_wsha+lg_NRSubWtKgN_wsha+lg_NwKgNWs_wsha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wsha+lg_NRSurWtKgN_wsha+lg_NRSubPdWtKgN_wsha+lg_NRSubWdWtKgN_wsha+lg_NwKgNWs_wsha, data=ndata))

m1 <- lm(lg_TN ~ lg_AllKgNWs_wsha, data=ndata)
m2 <- lm(lg_TN ~ lg_WtKgN_wsha+lg_NwKgNWs_wsha, data=ndata)
m3 <- lm(lg_TN ~ lg_RiparWtKgN_wsha+lg_NRWtKgN_wsha+lg_NwKgNWs_wsha, data=ndata)
m4 <- lm(lg_TN ~ lg_RiparWtKgN_wsha+lg_NRSurWtKgN_wsha+lg_NRSubWtKgN_wsha+lg_NwKgNWs_wsha, data=ndata)
m5 <- lm(lg_TN ~ lg_RiparWtKgN_wsha+lg_NRSurWtKgN_wsha+lg_NRSubPdWtKgN_wsha+lg_NRSubWdWtKgN_wsha+lg_NwKgNWs_wsha, data=ndata)

mods <- list(m1, m2, m3, m4, m5)
saveRDS(mods, paste0(nmodel_dir, '/model-objects/TN_per_wsarea.rds'))

```

## Divide watershed area (Y = N concentration)

* >2% wetlands

```{r, eval=F}
nmodel_dir <- 'D:/WorkFolder/WetlandConnectivity/WetConnect_Apr2019/nitrogen-modeling/'
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

#Riparian catchment goes into Canada
#ndata[ndata$COMID == 24120694, ]
ndata <- ndata[ndata$COMID != 24120694, ]
#Splitcat = single pixel at bottom of catchment
ndata <- ndata[ndata$SITE_ID != 'FW08MD001', ]

ndata$WtAreaHa <- rowSums(ndata[, grep('WtAreaHa', names(ndata), value=T)])
ndata$pctwt <- (ndata$WtAreaHa / ndata$WsAreaHa) * 100
ndata <- ndata[ndata$pctwt > 2, ]

ndata$lg_TN <- log10(ndata$TN)

ndata$NRWtKgN <- ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$lg_NRWtKgN_wsha <- log10((ndata$NRWtKgN / ndata$WsAreaHa)+1)
ndata$NRSubWtKgN <- ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$lg_NRSubWtKgN_wsha <- log10((ndata$NRSubWtKgN / ndata$WsAreaHa)+1)
ndata$lg_WtKgNWs_wsha <- log10((ndata$WtKgNWs / ndata$WsAreaHa)+1)

Types <- c('Ripar','NRSur','NRSubPd','NRSubWd')
for(i in 1:length(Types)){
  wt <- paste0(Types[i], c('WtKgN_wsha','WtKgN'))
  ndata[paste0('lg_',wt[1])] <- log10((ndata[wt[2]] / ndata$WsAreaHa)+1)
}

ndata$lg_NwKgNWs_wsha <- log10((ndata$NwKgNWs / ndata$WsAreaHa)+1)
ndata$lg_AllKgNWs_wsha <- log10((ndata$AllKgNWs / ndata$WsAreaHa)+1)


summary(lm(lg_TN ~ lg_AllKgNWs_wsha, data=ndata))

summary(lm(lg_TN ~ lg_WtKgNWs_wsha+lg_NwKgNWs_wsha, data=ndata))

summary(lm(lg_TN ~ lg_RiparWtKgN_wsha+lg_NRWtKgN_wsha+lg_NwKgNWs_wsha, data=ndata))

summary(lm(lg_TN ~ lg_RiparWtKgN_wsha+lg_NRSurWtKgN_wsha+lg_NRSubWtKgN_wsha+lg_NwKgNWs_wsha, data=ndata))

summary(lm(lg_TN ~ lg_RiparWtKgN_wsha+lg_NRSurWtKgN_wsha+lg_NRSubPdWtKgN_wsha+lg_NRSubWdWtKgN_wsha+lg_NwKgNWs_wsha, data=ndata))



```

## Divide wetland area

```{r, eval=F}
nmodel_dir <- 'D:/WorkFolder/WetlandConnectivity/WetConnect_Apr2019/nitrogen-modeling/'
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

#Riparian catchment goes into Canada
#ndata[ndata$COMID == 24120694, ]
ndata <- ndata[ndata$COMID != 24120694, ]
#Splitcat = single pixel at bottom of catchment
ndata <- ndata[ndata$SITE_ID != 'FW08MD001', ]

ndata$NonCatAreaHa <- ndata$WsAreaHa - ndata$WtCatAreaHaWs
ndata$WtAreaHa <- rowSums(ndata[,grep('WtAreaHa', names(ndata), value=T)])
Types <- c('Ripar','NRSur','NRSubPd','NRSubWd')

ndata$lg_TN <- log10(ndata$TN)

#Model1 data
ndata$lg_AllKgNWs_wsha <- log10((ndata$AllKgNWs / (ndata$WsAreaHa+1))+1)

#Model2 data
ndata$WtKgN <- ndata$RiparWtKgN + ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$lg_WtKgN_wtha <- log10((ndata$WtKgN / (ndata$WtAreaHa+1))+1)
ndata$lg_NwKgNWs_nwtha <- log10(ndata$NwKgNWs / ((ndata$NonCatAreaHa)+1))

#Model3 data
ndata$NRWtKgN <- ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$NRWtArea <- ndata$NRSurWtAreaHa + ndata$NRSubPdWtAreaHa + ndata$NRSubWdWtAreaHa
ndata$lg_NRWtKgN_wtha <- log10((ndata$NRWtKgN / (ndata$NRWtArea+1))+1)

#Model4 data
ndata$NRSubWtKgN <- ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$NRSubWtArea <- ndata$NRSubPdWtAreaHa + ndata$NRSubWdWtAreaHa
ndata$lg_NRSubWtKgN_wtha <- log10((ndata$NRSubWtKgN / (ndata$NRSubWtArea+1))+1)

#Model5 data
Types <- c('Ripar','NRSur','NRSubPd','NRSubWd')
for(i in 1:length(Types)){
  wt <- paste0(Types[i], c('WtKgN_wtha','WtKgN','WtAreaHa'))
  ndata[paste0('lg_',wt[1])] <- log10((ndata[wt[2]] / (ndata[wt[3]]+1))+1)
}

ndata <- ndata[ndata$lg_WtKgN_wtha > 0,]

plot(lg_TN ~ lg_WtKgN_wtha, data=ndata, pch=19, ylab='log10(TN [mg/L])', xlab='log10(TN Kg / watershed hectares)')

summary(lm(lg_TN ~ lg_WtKgN_wtha, data=ndata))

abline(lm(lg_TN ~ lg_WtKgN_wtha, data=ndata), col='darkorange', lwd=5)

plot(lg_WtKgN_wtha~lg_NwKgNWs_nwtha, data=ndata)
summary(lm(lg_WtKgN_wtha~lg_NwKgNWs_nwtha, data=ndata))



summary(lm(lg_TN ~ lg_AllKgNWs_wsha, data=ndata))
summary(lm(lg_TN ~ lg_WtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubPdWtKgN_wtha+lg_NRSubWdWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))

m1 <- lm(lg_TN ~ lg_AllKgNWs_wsha, data=ndata)
m2 <- lm(lg_TN ~ lg_WtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
m3 <- lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
m4 <- lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
m5 <- lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubPdWtKgN_wtha+lg_NRSubWdWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)

stepAIC(m6)$anova

m6 <- lm(lg_TN ~ lg_NRSurWtKgN_wtha+offset(lg_NRSurWtKgN_wtha)+ 
           lg_NRSubWdWtKgN_wtha + offset(lg_NRSubWdWtKgN_wtha)+ 
           lg_NwKgNWs_nwtha+offset(lg_NwKgNWs_nwtha)
         , data=ndata)
saveRDS(m6, paste0(nmodel_dir, '/model-objects/m6.rds'))
summary(m6)


mods <- list(m1, m2, m3, m4, m5)
saveRDS(mods, paste0(nmodel_dir, '/model-objects/TN_per_wtarea.rds'))


```

## Divide wetland area

* >2 wetland

```{r, eval=F}
nmodel_dir <- 'D:/WorkFolder/WetlandConnectivity/WetConnect_Apr2019/nitrogen-modeling/'
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

#Riparian catchment goes into Canada
#ndata[ndata$COMID == 24120694, ]
ndata <- ndata[ndata$COMID != 24120694, ]
#Splitcat = single pixel at bottom of catchment
ndata <- ndata[ndata$SITE_ID != 'FW08MD001', ]


ndata$WtAreaHa <- rowSums(ndata[, grep('WtAreaHa', names(ndata), value=T)])
ndata$pctwt <- (ndata$WtAreaHa / ndata$WsAreaHa) * 100
ndata <- ndata[ndata$pctwt > 2, ]

ndata$NonCatAreaHa <- ndata$WsAreaHa - ndata$WtCatAreaHaWs
ndata$WtAreaHa <- rowSums(ndata[,grep('WtAreaHa', names(ndata), value=T)])
Types <- c('Ripar','NRSur','NRSubPd','NRSubWd')

ndata$lg_TN <- log10(ndata$TN)

#Model1 data

ndata$lg_AllKgNWs_wsha <- log10((ndata$AllKgNWs / (ndata$WsAreaHa+1))+1)

#Model2 data
ndata$WtKgN <- ndata$RiparWtKgN + ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$lg_WtKgN_wtha <- log10((ndata$WtKgN / (ndata$WtAreaHa+1))+1)
ndata$lg_NwKgNWs_nwtha <- log10(ndata$NwKgNWs / ((ndata$NonCatAreaHa)+1))

#Model3 data
ndata$NRWtKgN <- ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$NRWtArea <- ndata$NRSurWtAreaHa + ndata$NRSubPdWtAreaHa + ndata$NRSubWdWtAreaHa
ndata$lg_NRWtKgN_wtha <- log10((ndata$NRWtKgN / (ndata$NRWtArea+1))+1)

#Model4 data
ndata$NRSubWtKgN <- ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$NRSubWtArea <- ndata$NRSubPdWtAreaHa + ndata$NRSubWdWtAreaHa
ndata$lg_NRSubWtKgN_wtha <- log10((ndata$NRSubWtKgN / (ndata$NRSubWtArea+1))+1)

#Model5 data
Types <- c('Ripar','NRSur','NRSubPd','NRSubWd')
for(i in 1:length(Types)){
  wt <- paste0(Types[i], c('WtKgN_wtha','WtKgN','WtAreaHa'))
  ndata[paste0('lg_',wt[1])] <- log10((ndata[wt[2]] / (ndata[wt[3]]+1))+1)
}

summary(lm(lg_TN ~ lg_AllKgNWs_wsha, data=ndata))

summary(lm(lg_TN ~ lg_WtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))

summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))

summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))

summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubPdWtKgN_wtha+lg_NRSubWdWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))
```

## Summary of wetland N inputs

```{r}
nmodel_dir <- 'D:/WorkFolder/WetlandConnectivity/WetConnect_Apr2019/nitrogen-modeling/'
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

#Riparian catchment goes into Canada
#ndata[ndata$COMID == 24120694, ]
ndata <- ndata[ndata$COMID != 24120694, ]
#Splitcat = single pixel at bottom of catchment
ndata <- ndata[ndata$SITE_ID != 'FW08MD001', ]

ndata$NRWtKgN <- ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$NRSubWtKgN <- ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN

tmp <- ndata[, grep('KgN', names(ndata), value=T)]
tmp <- log10(tmp + 1)
names(tmp) <- paste0('lg_', names(tmp))

tmp <- data.frame(lg_TNKgYr=log10(ndata$TNKgYr+1), tmp, DSlpWtWs=ndata$DSlpWtWs, DSlpWtNrWs=ndata$DSlpWtNrWs)

nrow(tmp)
nrow(tmp[tmp$lg_AllKgNWs > 0, ])
summary(tmp$lg_AllKgNWs)

nrow(tmp[tmp$lg_WtKgNWs > 0, ])
summary(tmp$lg_WtKgNWs)
summary(tmp$lg_WtKgNWs[tmp$lg_WtKgNWs > 0])

nrow(tmp[tmp$lg_RiparWtKgN > 0, ])
summary(tmp$lg_RiparWtKgN)
summary(tmp$lg_RiparWtKgN[tmp$lg_RiparWtKgN > 0])

nrow(tmp[tmp$lg_NRSurWtKgN > 0, ])
summary(tmp$lg_NRSurWtKgN)
summary(tmp$lg_NRSurWtKgN[tmp$lg_NRSurWtKgN > 0])

nrow(tmp[tmp$lg_NRSubPdWtKgN > 0, ])
summary(tmp$lg_NRSubPdWtKgN)
summary(tmp$lg_NRSubPdWtKgN[tmp$lg_NRSubPdWtKgN > 0])

nrow(tmp[tmp$lg_NRSubWdWtKgN > 0, ])
summary(tmp$lg_NRSubWdWtKgN)
summary(tmp$lg_NRSubWdWtKgN[tmp$lg_NRSubWdWtKgN > 0])

nrow(tmp[tmp$lg_NwKgNWs > 0, ])
summary(tmp$lg_NwKgNWs)
summary(tmp$lg_NwKgNWs[tmp$lg_NwKgNWs > 0])
```

## DOC

```{r}
nout <- read.csv(paste0(nmodel_dir, 'N.data.csv'))
nout <- subset(nout, select = c(SITE_ID, DOC))
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

cdata <- merge(ndata, nout)
cdata$lg_doc <- log10(cdata$DOC)
cdata$WtAreaHa <- rowSums(cdata[, grep('WtAreaHa', names(cdata))])

#Model1 data
cdata$lg_i_WsAreaHa <- log10(1/cdata$WsAreaHa)

#Model2 data
cdata$lg_i_WtAreaHa <- log10(1/cdata$WtAreaHa)
cdata$lg_i_WtAreaHa[is.infinite(cdata$lg_i_WtAreaHa)] <- 0

cdata$NonWtAreaHa <- cdata$WsAreaHa - cdata$WtAreaHa
cdata$lg_i_NonWtAreaHa <- log10(1/cdata$NonWtAreaHa)
cdata$lg_i_NonWtAreaHa[is.infinite(cdata$lg_i_NonWtAreaHa)] <- 0

#Model3 data
cdata$lg_i_RiparWtAreaHa <- log10(1/cdata$RiparWtAreaHa)
cdata$lg_i_RiparWtAreaHa[is.infinite(cdata$lg_i_RiparWtAreaHa)] <- 0

cdata$NRWtArea <- cdata$NRSurWtAreaHa + cdata$NRSubPdWtAreaHa + cdata$NRSubWdWtAreaHa
cdata$lg_i_NRWtArea <- log10(1/cdata$NRWtArea)
cdata$lg_i_NRWtArea[is.infinite(cdata$lg_i_NRWtArea)] <- 0

#Model4 data
cdata$lg_i_NRSurWtAreaHa <- log10(1/cdata$NRSurWtAreaHa)
cdata$lg_i_NRSurWtAreaHa[is.infinite(cdata$lg_i_NRSurWtAreaHa)] <- 0

cdata$NRSubWtArea <- cdata$NRSubPdWtAreaHa + cdata$NRSubWdWtAreaHa
cdata$lg_i_NRSubWtArea <- log10(1/cdata$NRSubWtArea)
cdata$lg_i_NRSubWtArea[is.infinite(cdata$lg_i_NRSubWtArea)] <- 0

#Model5 data
cdata$lg_i_NRSubWdWtAreaHa <- log10(1/cdata$NRSubWdWtAreaHa)
cdata$lg_i_NRSubWdWtAreaHa[is.infinite(cdata$lg_i_NRSubWdWtAreaHa)] <- 0

cdata$lg_i_NRSubPdWtAreaHa <- log10(1/cdata$NRSubPdWtAreaHa)
cdata$lg_i_NRSubPdWtAreaHa[is.infinite(cdata$lg_i_NRSubPdWtAreaHa)] <- 0



plot(lg_doc ~ lg_i_WtAreaHa, data=cdata, pch=19, ylab='log10(DOC [mg/L])', xlab='log10(1 / wetland area in watershed)')
abline(lm(lg_doc ~ lg_i_WtAreaHa, data=cdata), col='chartreuse3', lwd=5)


summary(lm(lg_doc ~ lg_i_WsAreaHa, data=cdata))
summary(lm(lg_doc ~ lg_i_WtAreaHa+lg_i_NonWtAreaHa, data=cdata))
summary(lm(lg_doc ~ lg_i_RiparWtAreaHa+lg_i_NRWtArea+lg_i_NonWtAreaHa, data=cdata))
summary(lm(lg_doc ~ lg_i_RiparWtAreaHa+lg_i_NRSurWtAreaHa+lg_i_NRSubWtArea+lg_i_NonWtAreaHa, data=cdata))
summary(lm(lg_doc ~ lg_i_RiparWtAreaHa+lg_i_NRSurWtAreaHa+lg_i_NRSubPdWtAreaHa+lg_i_NRSubWdWtAreaHa+lg_i_NonWtAreaHa, data=cdata))

m1 <- lm(lg_doc ~ lg_i_WsAreaHa, data=cdata)
m2 <- lm(lg_doc ~ lg_i_WtAreaHa+lg_i_NonWtAreaHa, data=cdata)
m3 <- lm(lg_doc ~ lg_i_RiparWtAreaHa+lg_i_NRWtArea+lg_i_NonWtAreaHa, data=cdata)
m4 <- lm(lg_doc ~ lg_i_RiparWtAreaHa+lg_i_NRSurWtAreaHa+lg_i_NRSubWtArea+lg_i_NonWtAreaHa, data=cdata)
m5 <- lm(lg_doc ~ lg_i_RiparWtAreaHa+lg_i_NRSurWtAreaHa+lg_i_NRSubPdWtAreaHa+lg_i_NRSubWdWtAreaHa+lg_i_NonWtAreaHa, data=cdata)


mods <- list(m1, m2, m3, m4, m5)
saveRDS(mods, paste0(nmodel_dir, '/model-objects/DOC_i_wtarea.rds'))


```

## DOC

* >2%

```{r}
nout <- read.csv(paste0(nmodel_dir, 'N.data.csv'))
nout <- subset(nout, select = c(SITE_ID, DOC))
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

cdata <- merge(ndata, nout)
cdata$lg_doc <- log10(cdata$DOC)
cdata$WtAreaHa <- rowSums(cdata[, grep('WtAreaHa', names(cdata))])

cdata$pctwt <- (cdata$WtAreaHa / cdata$WsAreaHa) * 100
cdata <- cdata[cdata$pctwt > 2, ]

#Model1 data
cdata$lg_i_WsAreaHa <- log10(1/cdata$WsAreaHa)

#Model2 data
cdata$lg_i_WtAreaHa <- log10(1/cdata$WtAreaHa)
cdata$lg_i_WtAreaHa[is.infinite(cdata$lg_i_WtAreaHa)] <- 0

cdata$NonWtAreaHa <- cdata$WsAreaHa - cdata$WtAreaHa
cdata$lg_i_NonWtAreaHa <- log10(1/cdata$NonWtAreaHa)
cdata$lg_i_NonWtAreaHa[is.infinite(cdata$lg_i_NonWtAreaHa)] <- 0

#Model3 data
cdata$lg_i_RiparWtAreaHa <- log10(1/cdata$RiparWtAreaHa)
cdata$lg_i_RiparWtAreaHa[is.infinite(cdata$lg_i_RiparWtAreaHa)] <- 0

cdata$NRWtArea <- cdata$NRSurWtAreaHa + cdata$NRSubPdWtAreaHa + cdata$NRSubWdWtAreaHa
cdata$lg_i_NRWtArea <- log10(1/cdata$NRWtArea)
cdata$lg_i_NRWtArea[is.infinite(cdata$lg_i_NRWtArea)] <- 0

#Model4 data
cdata$lg_i_NRSurWtAreaHa <- log10(1/cdata$NRSurWtAreaHa)
cdata$lg_i_NRSurWtAreaHa[is.infinite(cdata$lg_i_NRSurWtAreaHa)] <- 0

cdata$NRSubWtArea <- cdata$NRSubPdWtAreaHa + cdata$NRSubWdWtAreaHa
cdata$lg_i_NRSubWtArea <- log10(1/cdata$NRSubWtArea)
cdata$lg_i_NRSubWtArea[is.infinite(cdata$lg_i_NRSubWtArea)] <- 0

#Model5 data
cdata$lg_i_NRSubWdWtAreaHa <- log10(1/cdata$NRSubWdWtAreaHa)
cdata$lg_i_NRSubWdWtAreaHa[is.infinite(cdata$lg_i_NRSubWdWtAreaHa)] <- 0

cdata$lg_i_NRSubPdWtAreaHa <- log10(1/cdata$NRSubPdWtAreaHa)
cdata$lg_i_NRSubPdWtAreaHa[is.infinite(cdata$lg_i_NRSubPdWtAreaHa)] <- 0


summary(lm(lg_doc ~ lg_i_WsAreaHa, data=cdata))

summary(lm(lg_doc ~ lg_i_WtAreaHa+lg_i_NonWtAreaHa, data=cdata))

summary(lm(lg_doc ~ lg_i_RiparWtAreaHa+lg_i_NRWtArea+lg_i_NonWtAreaHa, data=cdata))

summary(lm(lg_doc ~ lg_i_RiparWtAreaHa+lg_i_NRSurWtAreaHa+lg_i_NRSubWtArea+lg_i_NonWtAreaHa, data=cdata))

summary(lm(lg_doc ~ lg_i_RiparWtAreaHa+lg_i_NRSurWtAreaHa+lg_i_NRSubPdWtAreaHa+lg_i_NRSubWdWtAreaHa+lg_i_NonWtAreaHa, data=cdata))

```


## DOC ~ % wetland

```{r}
nout <- read.csv(paste0(nmodel_dir, 'N.data.csv'))
nout <- subset(nout, select = c(SITE_ID, DOC))
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

cdata <- merge(ndata, nout)
cdata$lg_doc <- log10(cdata$DOC)
cdata$WtAreaHa <- rowSums(cdata[, grep('WtAreaHa', names(cdata))])

#cdata$pctwt <- (cdata$WtAreaHa / cdata$WsAreaHa) * 100
#cdata <- cdata[cdata$pctwt > 2, ]

cdata[paste0('pct_', grep('WtAreaHa', names(cdata), value=T))] <- (cdata[, grep('WtAreaHa', names(cdata), value=T)] / cdata$WsAreaHa) * 100

cdata[paste0('lg_', grep('pct_', names(cdata), value=T))] <- log10(cdata[, grep('pct_', names(cdata), value=T)] + 1)

#Model1 data
cdata$lg_WsAreaHa <- log10(cdata$WsAreaHa)

#Model2 data
cdata$NonWtAreaHa <- cdata$WsAreaHa - cdata$WtAreaHa
cdata$pct_NonWtAreaHa <- (cdata$NonWtAreaHa / cdata$WsAreaHa) * 100
cdata$lg_pct_NonWtAreaHa <- log10(cdata$pct_NonWtAreaHa+1)

#Model3 data
cdata$pct_NRWtArea <- ((cdata$pct_NRSurWtAreaHa + cdata$pct_NRSubPdWtAreaHa + cdata$pct_NRSubWdWtAreaHa) / cdata$WsAreaHa) * 100
cdata$lg_pct_NRWtArea <- log10(cdata$pct_NRWtArea+1)

#Model4 data
cdata$pct_NRSubWtArea <- ((cdata$pct_NRSubPdWtAreaHa + cdata$pct_NRSubWdWtAreaHa) / cdata$WsAreaHa) * 100
cdata$lg_pct_NRSubWtArea <- log10(cdata$pct_NRSubWtArea+1)



summary(lm(DOC ~ pct_WtAreaHa, data=cdata))

plot(lg_doc ~ lg_pct_WtAreaHa, data=cdata, pch=19, ylab='log10(DOC [mg/L])', xlab='log10(% wetland in watershed)')
abline(lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata), col='deepskyblue2', lwd=5)



abline(lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata), col='red', lwd=2)
plot(lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata))

cdata <- cdata[-993, ]
plot(doc ~ lg_pct_WtAreaHa, data=cdata)
summary(lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata))
abline(lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata), col='red', lwd=2)
plot(lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata))


plot()


hist(lm(lg_doc ~ pct_WtAreaHa, data=cdata)$residuals)


summary(lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata))

#summary(lm(lg_doc ~ lg_WsAreaHa, data=cdata))
summary(lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata))
summary(lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRWtArea, data=cdata))
summary(lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRSurWtAreaHa+lg_pct_NRSubWtArea, data=cdata))
summary(lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRSurWtAreaHa+lg_pct_NRSubPdWtAreaHa+lg_pct_NRSubWdWtAreaHa, data=cdata))

#m1 <- lm(lg_doc ~ lg_WsAreaHa, data=cdata)
m2 <- lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata)
m3 <- lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRWtArea, data=cdata)
m4 <- lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRSurWtAreaHa+lg_pct_NRSubWtArea, data=cdata)
m5 <- lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRSurWtAreaHa+lg_pct_NRSubPdWtAreaHa+lg_pct_NRSubWdWtAreaHa, data=cdata)

mods <- list(m2, m3, m4, m5)
saveRDS(mods, paste0(nmodel_dir, '/model-objects/DOC_PCT_wtarea.rds'))
```

## Divide wetland area / WATERSHED AREA

```{r, eval=F}
nmodel_dir <- 'D:/WorkFolder/WetlandConnectivity/WetConnect_Apr2019/nitrogen-modeling/'
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

#Riparian catchment goes into Canada
#ndata[ndata$COMID == 24120694, ]
ndata <- ndata[ndata$COMID != 24120694, ]
#Splitcat = single pixel at bottom of catchment
ndata <- ndata[ndata$SITE_ID != 'FW08MD001', ]

ndata$NonCatAreaHa <- ndata$WsAreaHa - ndata$WtCatAreaHaWs
ndata$WtAreaHa <- rowSums(ndata[,grep('WtAreaHa', names(ndata), value=T)])
Types <- c('Ripar','NRSur','NRSubPd','NRSubWd')

ndata$lg_TN <- log10(ndata$TN)

#Model1 data
ndata$lg_AllKgNWs_wsha <- log10((ndata$AllKgNWs / (ndata$WsAreaHa+1))+1)

#Model2 data
ndata$WtKgN <- ndata$RiparWtKgN + ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$lg_WtKgN_wtha <- log10((ndata$WtKgN / (ndata$WtAreaHa+1))+1)
ndata$lg_NwKgNWs_nwtha <- log10(ndata$NwKgNWs / ((ndata$NonCatAreaHa)+1))

#Model3 data
ndata$NRWtKgN <- ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$NRWtArea <- ndata$NRSurWtAreaHa + ndata$NRSubPdWtAreaHa + ndata$NRSubWdWtAreaHa
ndata$lg_NRWtKgN_wtha <- log10((ndata$NRWtKgN / (ndata$NRWtArea+1))+1)

#Model4 data
ndata$NRSubWtKgN <- ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$NRSubWtArea <- ndata$NRSubPdWtAreaHa + ndata$NRSubWdWtAreaHa
ndata$lg_NRSubWtKgN_wtha <- log10((ndata$NRSubWtKgN / (ndata$NRSubWtArea+1))+1)

#Model5 data
Types <- c('Ripar','NRSur','NRSubPd','NRSubWd')
for(i in 1:length(Types)){
  wt <- paste0(Types[i], c('WtKgN_wtha','WtKgN','WtAreaHa'))
  ndata[paste0('lg_',wt[1])] <- log10((ndata[wt[2]] / (ndata[wt[3]]+1))+1)
}

cor(ndata[, c(36:41)])
cor(ndata[, c('lg_WtKgN_wtha','lg_NwKgNWs_nwtha')])

summary(lm(lg_TN ~ lg_AllKgNWs_wsha, data=ndata))
summary(lm(lg_TN ~ lg_WtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubPdWtKgN_wtha+lg_NRSubWdWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))

m1 <- lm(lg_TN ~ lg_AllKgNWs_wsha, data=ndata)
m2 <- lm(lg_TN ~ lg_WtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
m3 <- lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
m4 <- lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
m5 <- lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubPdWtKgN_wtha+lg_NRSubWdWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)



mods <- list(m1, m2, m3, m4, m5)
saveRDS(mods, paste0(nmodel_dir, '/model-objects/TN_per_wtarea.rds'))


```
