---
title: "N Modeling"
author: "Ryan Hill"
date: "7/22/2019"
output: 
  html_document: 
    theme: yeti
---


## Divide wetland area

```{r, eval=F}
library(car)
library(randomForest)
nmodel_dir <- 'D:/WorkFolder/WetlandConnectivity/WetConnect_Oct2019/nitrogen-modeling/'
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

#Riparian catchment goes into Canada
#ndata[ndata$COMID == 24120694, ]
ndata <- ndata[ndata$COMID != 24120694, ]
#Splitcat = single pixel at bottom of catchment
ndata <- ndata[ndata$SITE_ID != 'FW08MD001', ]

ndata$NonCatAreaHa <- ndata$WsAreaHa - ndata$WtCatAreaHaWs
ndata$WtAreaHa <- rowSums(ndata[,grep('WtAreaHa', names(ndata), value=T)])
Types <- c('Ripar','NRSur','NRSubPd','NRSubWd')

ndata$lg_TN <- log10(ndata$TN)

#Model1 data
ndata$lg_AllKgNWs_wsha <- log10((ndata$AllKgNWs / (ndata$WsAreaHa+1))+1)

#Model2 data
ndata$WtKgN <- ndata$RiparWtKgN + ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$lg_WtKgN_wtha <- log10((ndata$WtKgN / (ndata$WtAreaHa+1))+1)
ndata$lg_NwKgNWs_nwtha <- log10(ndata$NwKgNWs / ((ndata$NonCatAreaHa)+1))

#Model3 data
ndata$NRWtKgN <- ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$NRWtArea <- ndata$NRSurWtAreaHa + ndata$NRSubPdWtAreaHa + ndata$NRSubWdWtAreaHa
ndata$lg_NRWtKgN_wtha <- log10((ndata$NRWtKgN / (ndata$NRWtArea+1))+1)

#Model4 data
ndata$NRSubWtKgN <- ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$NRSubWtArea <- ndata$NRSubPdWtAreaHa + ndata$NRSubWdWtAreaHa
ndata$lg_NRSubWtKgN_wtha <- log10((ndata$NRSubWtKgN / (ndata$NRSubWtArea+1))+1)

#Model5 data & RF model
ndata$NwKgNWs_nwtha <- ndata$NwKgNWs / ((ndata$NonCatAreaHa))
Types <- c('Ripar','NRSur','NRSubPd','NRSubWd')
for(i in 1:length(Types)){
  wt <- paste0(Types[i], c('WtKgN_wtha','WtKgN','WtAreaHa'))
  ndata[paste0('lg_',wt[1])] <- log10((ndata[wt[2]] / (ndata[wt[3]]+1))+1)
  ndata[wt[1]] <- (ndata[wt[2]] / (ndata[wt[3]]+1))
}

# <- ndata[ndata$lg_WtKgN_wtha > 0,]

plot(lg_TN ~ lg_WtKgN_wtha, data=ndata, pch=19, ylab='log10(TN [mg/L])', xlab='log10(TN Kg / watershed hectares)')
summary(lm(lg_TN ~ lg_WtKgN_wtha, data=ndata))
abline(lm(lg_TN ~ lg_WtKgN_wtha, data=ndata), col='darkorange', lwd=5)

summary(lm(lg_TN ~ lg_AllKgNWs_wsha, data=ndata))
summary(lm(lg_TN ~ lg_WtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))
summary(lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubPdWtKgN_wtha+lg_NRSubWdWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata))

m1 <- lm(lg_TN ~ lg_AllKgNWs_wsha, data=ndata)
m2 <- lm(lg_TN ~ lg_WtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
m3 <- lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
m4 <- lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
m5 <- lm(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubPdWtKgN_wtha+lg_NRSubWdWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
car::vif(m5)

mods <- list(m1, m2, m3, m4, m5)
saveRDS(mods, paste0(nmodel_dir, '/model-objects/TN_per_wtarea.rds'))

library(randomForest)
rf1 <- randomForest(lg_TN ~ lg_AllKgNWs_wsha, data=ndata)
rf2 <- randomForest(lg_TN ~ lg_WtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
rf3 <- randomForest(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
rf4 <- randomForest(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata)
rf5 <- randomForest(lg_TN ~ lg_RiparWtKgN_wtha+lg_NRSurWtKgN_wtha+lg_NRSubPdWtKgN_wtha+lg_NRSubWdWtKgN_wtha+lg_NwKgNWs_nwtha, data=ndata, importance=T)
varImpPlot(rf5)
partialPlot(rf5, ndata, lg_RiparWtKgN_wtha)
partialPlot(rf5, ndata, lg_NRSurWtKgN_wtha)
partialPlot(rf5, ndata, lg_NRSubPdWtKgN_wtha)
partialPlot(rf5, ndata, lg_NRSubWdWtKgN_wtha)
partialPlot(rf5, ndata, lg_NwKgNWs_nwtha)
```

## Compare slopes among predictors in TN models

```{r, eval=F}
library(utils)
library(car)

mods <- readRDS(paste0(nmodel_dir, '/model-objects/TN_per_wtarea.rds'))

#Compare parameters in model with just 2 predictors (wetland and non-wetland N inputs)
mod <- mods[2][[1]]
nms <- names(mod$coefficients)[2:length(names(mod$coefficients))]
combos <- combn(nms, 2)
for(i in 1:ncol(combos)){
  print(combos[, i])
  ccc <- combos[, i]
  test <- paste0(ccc[1], ' = ', ccc[2])
  print(linearHypothesis(mod, test))
  print("---------------------------------------------------------------------------------------")
}

#Compare parameters in model with 3 predictors (riparian, non-riparian, non-wetland N inputs)
mod <- mods[3][[1]]
nms <- names(mod$coefficients)[2:length(names(mod$coefficients))]
combos <- combn(nms, 2)
for(i in 1:ncol(combos)){
  print(combos[, i])
  ccc <- combos[, i]
  test <- paste0(ccc[1], ' = ', ccc[2])
  print(linearHypothesis(mod, test))
  print("---------------------------------------------------------------------------------------")
}

#Compare parameters in model with 4 predictors (riparian, non-riparian surface, non-riparian subsurface, non-wetland N inputs)
mod <- mods[4][[1]]
nms <- names(mod$coefficients)[2:length(names(mod$coefficients))]
combos <- combn(nms, 2)
for(i in 1:ncol(combos)){
  print(combos[, i])
  ccc <- combos[, i]
  test <- paste0(ccc[1], ' = ', ccc[2])
  print(linearHypothesis(mod, test))
  print("---------------------------------------------------------------------------------------")
}

#Compare parameters in model with 5 predictors (riparian, non-riparian surface, non-riparian subsurface, non-wetland N inputs)
mod <- mods[5][[1]]
nms <- names(mod$coefficients)[2:length(names(mod$coefficients))]
combos <- combn(nms, 2)
for(i in 1:ncol(combos)){
  print(combos[, i])
  ccc <- combos[, i]
  test <- paste0(ccc[1], ' = ', ccc[2])
  print(linearHypothesis(mod, test))
  print("---------------------------------------------------------------------------------------")
}
```


## Summary of wetland N inputs

```{r}
nmodel_dir <- 'D:/WorkFolder/WetlandConnectivity/WetConnect_Oct2019/nitrogen-modeling/'
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

#Riparian catchment goes into Canada
#ndata[ndata$COMID == 24120694, ]
ndata <- ndata[ndata$COMID != 24120694, ]
#Splitcat = single pixel at bottom of catchment
ndata <- ndata[ndata$SITE_ID != 'FW08MD001', ]

ndata$NRWtKgN <- ndata$NRSurWtKgN + ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN
ndata$NRSubWtKgN <- ndata$NRSubPdWtKgN + ndata$NRSubWdWtKgN

tmp <- ndata[, grep('KgN', names(ndata), value=T)]
tmp <- log10(tmp + 1)
names(tmp) <- paste0('lg_', names(tmp))

tmp <- data.frame(lg_TNKgYr=log10(ndata$TNKgYr+1), tmp, DSlpWtWs=ndata$DSlpWtWs, DSlpWtNrWs=ndata$DSlpWtNrWs)

nrow(tmp)
nrow(tmp[tmp$lg_AllKgNWs > 0, ])
summary(tmp$lg_AllKgNWs)

nrow(tmp[tmp$lg_WtKgNWs > 0, ])
summary(tmp$lg_WtKgNWs)
summary(tmp$lg_WtKgNWs[tmp$lg_WtKgNWs > 0])

nrow(tmp[tmp$lg_RiparWtKgN > 0, ])
summary(tmp$lg_RiparWtKgN)
summary(tmp$lg_RiparWtKgN[tmp$lg_RiparWtKgN > 0])

nrow(tmp[tmp$lg_NRSurWtKgN > 0, ])
summary(tmp$lg_NRSurWtKgN)
summary(tmp$lg_NRSurWtKgN[tmp$lg_NRSurWtKgN > 0])

nrow(tmp[tmp$lg_NRSubPdWtKgN > 0, ])
summary(tmp$lg_NRSubPdWtKgN)
summary(tmp$lg_NRSubPdWtKgN[tmp$lg_NRSubPdWtKgN > 0])

nrow(tmp[tmp$lg_NRSubWdWtKgN > 0, ])
summary(tmp$lg_NRSubWdWtKgN)
summary(tmp$lg_NRSubWdWtKgN[tmp$lg_NRSubWdWtKgN > 0])

nrow(tmp[tmp$lg_NwKgNWs > 0, ])
summary(tmp$lg_NwKgNWs)
summary(tmp$lg_NwKgNWs[tmp$lg_NwKgNWs > 0])
```


## DOC ~ % wetland

```{r}
nout <- read.csv(paste0(nmodel_dir, 'N.data.csv'))
nout <- subset(nout, select = c(SITE_ID, DOC))
ndata <- read.csv(paste0(nmodel_dir, 'splitcat-metrics/nmodel-data.csv'))

cdata <- merge(ndata, nout)
cdata$lg_doc <- log10(cdata$DOC)
cdata$WtAreaHa <- rowSums(cdata[, grep('WtAreaHa', names(cdata))])

#cdata$pctwt <- (cdata$WtAreaHa / cdata$WsAreaHa) * 100
#cdata <- cdata[cdata$pctwt > 2, ]

cdata[paste0('pct_', grep('WtAreaHa', names(cdata), value=T))] <- (cdata[, grep('WtAreaHa', names(cdata), value=T)] / cdata$WsAreaHa) * 100

cdata[paste0('lg_', grep('pct_', names(cdata), value=T))] <- log10(cdata[, grep('pct_', names(cdata), value=T)] + 1)

#Model1 data
cdata$lg_WsAreaHa <- log10(cdata$WsAreaHa)

#Model2 data
cdata$NonWtAreaHa <- cdata$WsAreaHa - cdata$WtAreaHa
cdata$pct_NonWtAreaHa <- (cdata$NonWtAreaHa / cdata$WsAreaHa) * 100
cdata$lg_pct_NonWtAreaHa <- log10(cdata$pct_NonWtAreaHa+1)

#Model3 data
cdata$pct_NRWtArea <- ((cdata$pct_NRSurWtAreaHa + cdata$pct_NRSubPdWtAreaHa + cdata$pct_NRSubWdWtAreaHa) / cdata$WsAreaHa) * 100
cdata$lg_pct_NRWtArea <- log10(cdata$pct_NRWtArea+1)

#Model4 data
cdata$pct_NRSubWtArea <- ((cdata$pct_NRSubPdWtAreaHa + cdata$pct_NRSubWdWtAreaHa) / cdata$WsAreaHa) * 100
cdata$lg_pct_NRSubWtArea <- log10(cdata$pct_NRSubWtArea+1)

#hist(lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata)$residuals)


#summary(lm(lg_doc ~ lg_WsAreaHa, data=cdata))
summary(lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata))
summary(lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRWtArea, data=cdata))
summary(lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRSurWtAreaHa+lg_pct_NRSubWtArea, data=cdata))
summary(lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRSurWtAreaHa+lg_pct_NRSubPdWtAreaHa+lg_pct_NRSubWdWtAreaHa, data=cdata))

#m1 <- lm(lg_doc ~ lg_WsAreaHa, data=cdata)
m2 <- lm(lg_doc ~ lg_pct_WtAreaHa, data=cdata)
m3 <- lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRWtArea, data=cdata)
m4 <- lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRSurWtAreaHa+lg_pct_NRSubWtArea, data=cdata)
m5 <- lm(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRSurWtAreaHa+lg_pct_NRSubPdWtAreaHa+lg_pct_NRSubWdWtAreaHa, data=cdata)

mods <- list(m2, m3, m4, m5)
saveRDS(mods, paste0(nmodel_dir, '/model-objects/DOC_PCT_wtarea.rds'))

library(randomForest)
rf1 <- randomForest(lg_doc ~ lg_pct_WtAreaHa, data=cdata)
rf2 <- randomForest(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRWtArea, data=cdata)
rf3 <- randomForest(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRSurWtAreaHa+lg_pct_NRSubWtArea, data=cdata)
rf4 <- randomForest(lg_doc ~ lg_pct_RiparWtAreaHa+lg_pct_NRSurWtAreaHa+lg_pct_NRSubPdWtAreaHa+lg_pct_NRSubWdWtAreaHa, data=cdata, importance=T)
varImpPlot(rf4)
partialPlot(rf4, cdata, lg_pct_RiparWtAreaHa)
partialPlot(rf4, cdata, lg_pct_NRSurWtAreaHa)
partialPlot(rf4, cdata, lg_pct_NRSubPdWtAreaHa)
partialPlot(rf4, cdata, lg_pct_NRSubWdWtAreaHa)
```


## Compare slopes among predictors in DOC models

```{r, eval=F}
library(utils)
library(car)

mods <- readRDS(paste0(nmodel_dir, '/model-objects/DOC_PCT_wtarea.rds'))

#Compare parameters in model with just 2 predictors (% riparian and % non-riparian)
mod <- mods[2][[1]]
nms <- names(mod$coefficients)[2:length(names(mod$coefficients))]
combos <- combn(nms, 2)
for(i in 1:ncol(combos)){
  print(combos[, i])
  ccc <- combos[, i]
  test <- paste0(ccc[1], ' = ', ccc[2])
  print(linearHypothesis(mod, test))
  print("---------------------------------------------------------------------------------------")
}

#Compare parameters in model with 3 predictors (% riparian, % surface, % subsurface)
mod <- mods[3][[1]]
nms <- names(mod$coefficients)[2:length(names(mod$coefficients))]
combos <- combn(nms, 2)
for(i in 1:ncol(combos)){
  print(combos[, i])
  ccc <- combos[, i]
  test <- paste0(ccc[1], ' = ', ccc[2])
  print(linearHypothesis(mod, test))
  print("---------------------------------------------------------------------------------------")
}

#Compare parameters in model with 4 predictors (% riparian, % surface, % subsurface poorly drained, % surbsurface well drained)
mod <- mods[4][[1]]
nms <- names(mod$coefficients)[2:length(names(mod$coefficients))]
combos <- combn(nms, 2)
for(i in 1:ncol(combos)){
  print(combos[, i])
  ccc <- combos[, i]
  test <- paste0(ccc[1], ' = ', ccc[2])
  print(linearHypothesis(mod, test))
  print("---------------------------------------------------------------------------------------")
}
```
